# 1 anchor, 5 aug anchor, 1 other real, 3 vocoded, 3 aug vocoded - with RawBoost only, 1 other spoof
model:
  name: wav2vec2_aasist
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  aasist:
    filts: [128, [1, 32], [32, 32], [32, 64], [64, 64]]
    gat_dims: [64, 32]
    pool_ratios: [0.5, 0.5, 0.5, 0.5]
    temperatures: [2.0, 2.0, 100.0, 100.0]
    nclasses: 5
  xlsr: 
    num_layers: null
    order: 'first'
    custom_order: null
  
data:
  # name: 'asvspoof_2019_augall_3'
  name: 'eval_only'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12", "background_noise_wrapper", "reverb_wrapper"]
    num_additional_real: 1
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/datab/phucdt/Asvspoof_aug/asvspoof2019'
    noise_path: '/datab/Dataset/Noise/musan'
    rir_path: '/datab/Dataset/Noise/RIRS_NOISES'