model:
  name: rawnet3_conformer
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  conformer:
    emb_size: 144
    heads: 4
    kernel_size: 31
    n_encoders: 4
    pooling: 'max' # mean, max or first_token
data:
  name: 'SCL_normal'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ['RawBoost12', 'background_noise_wrapper', 'reverb_wrapper', 'gaussian_noise_wrapper']
    num_additional_real: 2
    num_additional_spoof: 3
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/datab/phucdt/Asvspoof_aug/asvspoof2019'
    noise_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/musan'
    rir_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/RIRS_NOISES'