# 1 anchor, 5 aug anchor, 1 other real, 3 vocoded, 3 aug vocoded - with RawBoost only, 1 other spoof
model:
  name: wavlm_vib_gelu_multi_huggingface
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  recon_weight_l: 0.000001
  recon_weight_b: 0.05
  xlsr: 
    num_layers: 9
    order: 'first'
    custom_order: null
data:
  name: 'acmccs_augall_5'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12", "background_noise_wrapper", "reverb_wrapper", "telephone_wrapper", "gaussian_noise_wrapper"]
    num_additional_real: 1
    num_additional_spoof: 2
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/datab/phucdt/Asvspoof_aug/asvspoof2019'
    noise_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/musan'
    rir_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/RIRS_NOISES'