# 1 anchor, 5 aug anchor, 1 other real, 3 vocoded, 3 aug vocoded - with RawBoost only, 1 other spoof
model:
  name: wav2vec2_vib_gelu
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  recon_weight_l: 0.000001
  recon_weight_b: 0.05
  xlsr: 
    num_layers: 24
    order: 'first'
    custom_order: null
data:
  # portion: 0.2 # test with 0.01 dataset
  name: 'acmccs_augall_7'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoostFull", "background_noise_3_20", "reverb_1", "telephone_g722", "gaussian_1", 'mp32flac', 'ogg2flac', 'nonspeechtrim', "volume_10", "echo_1"]
    num_additional_real: 1
    num_additional_spoof: 1
    trim_length: 64600 # 4s
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/dataa/phucdt/vocodetect/traindata/augment_tmp'
    noise_path: '/datab/Dataset/Noise/musan/'
    rir_path: '/datab/Dataset/Noise/RIRS_NOISES'