model:
  name: wav2vec2_linear_nll
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only, 4: only loss CE (no contrastive loss)
  resnet:
    num_nodes: 3
    enc_dim: 256
    resnet_type: '18'
    nclasses: 2
data:
  name: 'normal'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12"]
    num_additional_real: 2
    trim_length: 64000
    wav_samp_rate: 16000
