model:
  name: wav2vec2_resnet
  flag_fix_ssl: false
  contra_mode: 'one' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only
  resnet:
    num_nodes: 3
    enc_dim: 256
    resnet_type: '18'
    nclasses: 2
data:
  name: 'eval_only'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf', 'hn-sinc-nsf-hifi', 'waveglow', 'melgan']
    augmentation_methods: ["RawBoost12"]
    num_additional_real: 2
    trim_length: 64000
    wav_samp_rate: 16000