model:
  name: wav2vec2_linear_phucdt
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 2 # 1: 2loss, 2: loss feat only, 3: loss emb
  K: 1 # number of augmentations
  S: 5 # number of vocoders
data:
  name: 'asvspoof_2019'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf', 'hn-sinc-nsf-hifi', 'waveglow', 'melgan']
    augmentation_methods: ["RawBoost12"]
    num_additional_real: 2
    trim_length: 64000
    wav_samp_rate: 16000