optimizer: Adam 
amsgrad: 1   #for adam optim
lr: 0.00001

#model-related
model:
  in_channels: 110
  n_enc_layers: 3
  enc: [[110, 128], [128, 256], [256, 512]]

  n_dec_layers: 2
  dec: [[256, 128], [128, 110]] # out channel == in_channel
  vae_rate: 0.001
  nb_classes: 2


dataset:
  feat_type: 'mpd_ys_102'

  
# #model-related
# model:
#   nb_classes: 2
#   spec_channels: 768
#   inter_channels: 512
#   hidden_channels: 512
#   kernel_size_dec: 5
#   dilation_rate: 1
#   n_enc_layers: 16
#   n_flow_layers: 4
#   gin_channels: 0
#   fc1_channels: 512
#   fc2_channels: 512
#   nb_gru_layer: 3

# dataset:
#   feat_dir: './feats/'
#   max_wav_value: 32768.0
#   sampling_rate: 16000
#   filter_length: 1024
#   hop_length: 256
#   win_length: 1024
  
  



